name: Build Gatsby and deploy to Netlify

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
        env:
          CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY}}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY}}
          AMAZON_HOST: ${{ secrets.AMAZON_HOST}}
          AMAZON_REGION: ${{ secrets.AMAZON_REGION}}
          AMAZON_PARTNER_TAG: ${{ secrets.AMAZON_PARTNER_TAG }}
          AMAZON_PARTNER_TYPE: ${{ secrets.AMAZON_PARTNER_TYPE}}
      - name: Commit amazon-list.yaml
        uses: EndBug/add-and-commit@v6
        with:
          add: 'content/amazon-list.yaml'
          message: 'add new amazon link data'
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --functions=functions --prod --message=\"Deploy from GitHub Actions\"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}